/**
 * inphner: turn the vendored cubing/icons event SVGs (MIT, src/data/event-icons/,
 * from github.com/cubing/icons @ 3.0.5) into src/data/event-icons.ts: one
 * { viewBox, body } per event, filled with currentColor so they follow the
 * surrounding text colour. Run: node tools/event-icons.mjs
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dir = join(root, 'src/data/event-icons');
const out = {};
for (const file of readdirSync(dir).filter((f) => f.endsWith('.svg')).sort()) {
  const svg = readFileSync(join(dir, file), 'utf8');
  const viewBox = /viewBox="([^"]+)"/.exec(svg)?.[1] ?? '0 0 500 500';
  const body = svg
    .replace(/^[\s\S]*?<svg[^>]*>/, '')
    .replace(/<\/svg>\s*$/, '')
    .replace(/\s(fill|style|class|id)="[^"]*"/g, '')
    .replace(/\s+/g, ' ')
    .trim();
  if (/<script|on\w+=|href/i.test(body)) throw new Error(`unexpected content in ${file}`);
  out[file.replace(/\.svg$/, '')] = { viewBox, body };
}
const ts = `/**
 * GENERATED by tools/event-icons.mjs from src/data/event-icons/*.svg.
 * WCA event icons from cubing/icons 3.0.5 (MIT, Copyright (c) 2015 Devin Corr-Robinett).
 */
export const EVENT_ICONS: Record<string, { viewBox: string; body: string }> = ${JSON.stringify(out, null, 2)};
`;
writeFileSync(join(root, 'src/data/event-icons.ts'), ts);
console.log(`[inphner] ${Object.keys(out).length} event icons → src/data/event-icons.ts`);
